services:
  react-tasks-app:
    build:
      context: ./react-client
    ports:
      - "8080:80"
    depends_on:
      - node-tasks-app-service
    networks:
      - frontend
  node-tasks-app-service:
    build: ./tasks-api
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGODB_URI=mongodb://mongodb:27017/tasks
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
