services:
  react-tasks-app:
    build:
      context: ./react-client
    image: eswarmaganti/react-tasks-app:latest
    ports:
      - "3000:80"
    depends_on:
      - node-tasks-app-service
    networks:
      - frontend
    pull_policy: always
  node-tasks-app-service:
    build: ./tasks-api
    image: eswarmaganti/node-tasks-app:latest
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGODB_URI=mongodb://mongodb:27017/tasks
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    pull_policy: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    pull_policy: if_not_present
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
