services:
  react-tasks-app:
    build:
      context: ./react-client
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: eswarmaganti/react-tasks-app
    ports:
      - "8081:80"
    depends_on:
      - node-tasks-api
    networks:
      - frontend
  node-tasks-api:
    build: ./tasks-api
    image: eswarmaganti/node-tasks-api
    ports:
      - "5051:5050"
    environment:
      - PORT=5050
      - MONGODB_URI=mongodb://mongodb:27017/tasks
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27016:27017"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
